defaults:
  -
    scope:
      type: posts
    values:
      layout: post
  -
    scope:
      type: drafts
    values:
      layout: post
timezone: US/Pacific
icon: https://avatars.githubusercontent.com/u/382696?v=3
feed_author_name: Awesome
feed_base: http://hub.sourcesquarechina.online/paper/
feed_id_authority: http://hub.sourcesquarechina.online/paper/
